version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            # "DATABASE_URL":"postgres://cabopddzbwndhr:3b180249a17ed7fdb178a5d23e8ee9ac443abaf177e16fa201f9df260c156a73@ec2-18-232-143-90.compute-1.amazonaws.com:5432/dsj3ddmj1mlto"
            connector: postgres
            host: ec2-18-232-143-90.compute-1.amazonaws.com
            port: 5432
            database: dsj3ddmj1mlto
            user: cabopddzbwndhr
            password: 3b180249a17ed7fdb178a5d23e8ee9ac443abaf177e16fa201f9df260c156a73
            ssl: true
            rawAccess: true
            migrations: true
#   postgres:
#     image: postgres
#     restart: always
#     # Uncomment the next two lines to connect to your your database from outside the Docker environment, e.g. using a database GUI like Postico
#     # ports:
#     # - "5432:5432"
#     environment:
#       POSTGRES_USER: prisma
#       POSTGRES_PASSWORD: prisma
#     volumes:
#       - postgres:/var/lib/postgresql/data
# volumes:
#   postgres:
